import {Text} from "@chakra-ui/react";
import Head from 'next/head'
import { useAccount } from "wagmi";
import { Layout } from "@/components/Layout/Layout";
import Addajob from "@/components/Addajob/Addajob";

export default function Home() {

return (
    <>
    <Head>
        <title>Minijob Dapp</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
    </Head>
    <Layout>
        <Addajob/>
    </Layout>
    </>
)}