import Head from "next/head";
import { Layout } from "@/components/Layout/Layout";
import React from "react";
import { Alert, AlertIcon, Flex } from "@chakra-ui/react";
import Listjobs from "@/components/Listjobs/Listjobs";

export default function Home() {
  return (
    <>
      <Head>
        <title>Minijob Dapp</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Layout>
          <Listjobs />
      </Layout>
    </>
  );
}
